// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdIvlE-TFNuOoo6z4bKM3iRgYnCnpwm4',
    appId: '1:89750409201:web:bec3cbb1aaa8827242be50',
    messagingSenderId: '89750409201',
    projectId: 'medimind-368ed',
    authDomain: 'medimind-368ed.firebaseapp.com',
    storageBucket: 'medimind-368ed.firebasestorage.app',
    measurementId: 'G-TYLKRSVHMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACrnOI24MUd-6DlTM69CtxxB2WBKvW1Y',
    appId: '1:89750409201:android:4eccc458abe9469142be50',
    messagingSenderId: '89750409201',
    projectId: 'medimind-368ed',
    storageBucket: 'medimind-368ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFEv15b2lxpiFb_Kc7z7HCWyKACjRYcsM',
    appId: '1:89750409201:ios:3052604551a5e2c542be50',
    messagingSenderId: '89750409201',
    projectId: 'medimind-368ed',
    storageBucket: 'medimind-368ed.firebasestorage.app',
    iosBundleId: 'com.example.medimind',
  );
}
